version: "3"
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: "book-table"
    ports:
      - "8080:8080"
    volumes:
      - ./front:/usr/src/front
      - /usr/src/front/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "server-book-table"
    ports:
      - "3000:3000"
    volumes:
      - ./server:/home/server
      - /home/server/node_modules
