version: "3"
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: "book-table"
    ports:
      - "8080:8080"
    volumes:
      - ./front:/usr/src/front
      - /usr/src/front/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "server-book-table"
    environment:
      - PORT=5000
      - URL=http://localhost
      - MONGO_URL=mongodb://database:27017
      - DB_NAME=bookTableLocal
      - API_VERSION=v1
    ports:
      - "5000:5000"
    volumes:
      - ./server:/home/server
      - /home/server/node_modules
  database:
    image: mongo:latest
    container_name: database
    volumes:
      - mongodb_api:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_api:
